package com.bc230420212.app.data.model

import java.util.Date

/**
 * DISASTER REPORT DATA MODEL
 * 
 * This data class represents a disaster report in the app.
 * It contains all the information about a reported disaster.
 * 
 * @param id - Unique ID of the report (generated by Firestore)
 * @param userId - ID of the user who created the report
 * @param disasterType - Type of disaster (Flood, Fire, etc.)
 * @param description - Description of the disaster
 * @param latitude - GPS latitude coordinate
 * @param longitude - GPS longitude coordinate
 * @param address - Human-readable address (optional)
 * @param mediaUrls - List of photo/video URLs from Firebase Storage
 * @param timestamp - When the report was created
 * @param status - Status of the report (ACTIVE, RESOLVED, FALSE_ALARM)
 * @param confirmations - Number of users who confirmed this report
 * @param dismissals - Number of users who dismissed this report
 * @param confirmedBy - List of user IDs who have confirmed this report (for one-time voting)
 * @param dismissedBy - List of user IDs who have dismissed this report (for one-time voting)
 */
data class DisasterReport(
    val id: String = "",
    val userId: String = "",
    val disasterType: DisasterType = DisasterType.OTHER,
    val description: String = "",
    val latitude: Double = 0.0,
    val longitude: Double = 0.0,
    val address: String = "",
    val mediaUrls: List<String> = emptyList(),
    val timestamp: Long = System.currentTimeMillis(),
    val status: ReportStatus = ReportStatus.ACTIVE,
    val confirmations: Int = 0,
    val dismissals: Int = 0,
    val confirmedBy: List<String> = emptyList(),
    val dismissedBy: List<String> = emptyList()
)

/**
 * REPORT STATUS ENUM
 * 
 * Defines the possible statuses of a disaster report.
 */
enum class ReportStatus {
    ACTIVE,      // Report is active and needs attention
    VERIFIED,    // Report has been verified by admin
    RESOLVED,    // Report has been resolved
    FALSE_ALARM  // Report was a false alarm
}

