package com.bc230420212.app.data.model

/**
 * SOS ALERT DATA MODEL
 * 
 * This data class represents an SOS emergency alert in the app.
 * It contains all the information about an emergency alert.
 * 
 * @param id - Unique ID of the alert (generated by Firestore)
 * @param userId - ID of the user who sent the alert
 * @param userEmail - Email of the user who sent the alert
 * @param userName - Name of the user who sent the alert
 * @param latitude - GPS latitude coordinate at time of alert
 * @param longitude - GPS longitude coordinate at time of alert
 * @param address - Human-readable address (optional)
 * @param timestamp - When the alert was sent
 * @param status - Status of the alert (ACTIVE, RESPONDED, RESOLVED)
 * @param message - Optional message from the user
 */
data class SOSAlert(
    val id: String = "",
    val userId: String = "",
    val userEmail: String = "",
    val userName: String = "",
    val latitude: Double = 0.0,
    val longitude: Double = 0.0,
    val address: String = "",
    val timestamp: Long = System.currentTimeMillis(),
    val status: SOSStatus = SOSStatus.ACTIVE,
    val message: String = ""
)

/**
 * SOS STATUS ENUM
 * 
 * Defines the possible statuses of an SOS alert.
 */
enum class SOSStatus {
    ACTIVE,      // Alert is active and needs response
    RESPONDED,   // Alert has been responded to
    RESOLVED     // Alert has been resolved
}

